[package]
name = "scraper-extras"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cssparser = "0.29.2"
ego-tree = "0.6.2"
scraper = "0.12.0"
selectors = "0.23.0"
